

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        first:  #数据源1
            url: jdbc:mysql://localhost:3306/rcs_c?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
            
   
     
      
            
      
      
            driver-class-name: com.mysql.jdbc.Driver
        second:  #数据源2
            url: jdbc:postgresql://localhost:3306/gulou?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: postgres
            password: postgres
            driver-class-name: org.postgresql.Driver
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            login-username: admin
            login-password: admin
        filter:
            stat:
                log-slow-sql: true
                slow-sql-millis: 1000
                merge-sql: true
            wall:
                config:
                    multi-statement-allow: true
 
  
  redis: 
    database : 2
    host: 127.0.0.1
    port: 6379  
    password: 123456
    max-active: 1024
    pool: 
      max-wait: -1  
      max-idle: 50
      min-idle: 0  
      
   # 上传文件
  servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB
        file-size-threshold: 1MB
   

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否将自己注册到Eureka服务中，默认为true
    fetch--registry: true #是否从Eureka中获取注册信息，默认为true
    service-url:
      defaultZone: http://localhost:8000/eureka/
      
#开启Hystrix熔断器
feign:
  hystrix:  
    enabled: true
    
    
test:
  test1 : aaa
  test2 : bbb

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


    
    
